# Generated by Django 4.2.30 on 2026-08-19 06:45

from django.db import migrations, models
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pghistory', '0007_auto_20250421_0444'),
        ('organization', '0011_organization_funder'),
        ('program', '0017_delete_managedopportunity'),
    ]

    operations = [
        # The M2M table program_program_watchers already exists, created by migration 0016 as
        # Django's auto-generated through table. ProgramWatcher adopts that same table so
        # pghistory can attach triggers to it, so this is a state-only change: the columns
        # and rows are untouched, only Django's model registry changes.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='ProgramWatcher',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ],
                    options={
                        'db_table': 'program_program_watchers',
                    },
                ),
                migrations.AddField(
                    model_name='programwatcher',
                    name='organization',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
                ),
                migrations.AddField(
                    model_name='programwatcher',
                    name='program',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.program'),
                ),
                migrations.AlterUniqueTogether(
                    name='programwatcher',
                    unique_together={('program', 'organization')},
                ),
                migrations.AlterField(
                    model_name='program',
                    name='watchers',
                    field=models.ManyToManyField(blank=True, related_name='watched_programs', through='program.ProgramWatcher', to='organization.organization'),
                ),
            ],
        ),
        migrations.CreateModel(
            name='ProgramFunderEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramWatcherEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='program',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "program_programfunderevent" ("funder_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."funder_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id"); RETURN NULL;', hash='e5a5bf800c6e76854b764eb649e44f323af759a5', operation='INSERT', pgid='pgtrigger_insert_insert_98c63', table='program_program', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='program',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."funder_id" IS DISTINCT FROM (NEW."funder_id"))', func='INSERT INTO "program_programfunderevent" ("funder_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."funder_id", _pgh_attach_context(), NOW(), \'update\', NEW."id"); RETURN NULL;', hash='35a396ed010fac4650becc8672dc9de95069cf7b', operation='UPDATE', pgid='pgtrigger_update_update_dcb32', table='program_program', when='AFTER')),
        ),
        migrations.AddField(
            model_name='programwatcherevent',
            name='organization',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='programwatcherevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='programwatcherevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='program.programwatcher'),
        ),
        migrations.AddField(
            model_name='programwatcherevent',
            name='program',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='program.program'),
        ),
        migrations.AddField(
            model_name='programfunderevent',
            name='funder',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='programfunderevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='programfunderevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='funder_events', to='program.program'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='programwatcher',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "program_programwatcherevent" ("id", "organization_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "program_id") VALUES (NEW."id", NEW."organization_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."program_id"); RETURN NULL;', hash='dd78a603722f70bf5c5c839aafccfaaca8c2541f', operation='INSERT', pgid='pgtrigger_insert_insert_86519', table='program_program_watchers', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='programwatcher',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "program_programwatcherevent" ("id", "organization_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "program_id") VALUES (OLD."id", OLD."organization_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."program_id"); RETURN NULL;', hash='508a2ab2a7763c4da060f1c6c68d415449d1150d', operation='DELETE', pgid='pgtrigger_delete_delete_b4b84', table='program_program_watchers', when='AFTER')),
        ),
    ]
