# Generated by Django 5.2.17 on 2026-09-10 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0018_programapplication_unique_program_application_per_organization'),
        ('program', '0018_programfunderevent_programwatcher_and_more'),
    ]

    operations = [
    ]
