AUTOMATIC_VISIT_VERIFICATION = "automatic_visit_verification"
OPPORTUNITY_CREDENTIALS = "opportunity_credentials"
API_UUID = "api_uuid"
WORKER_VISITS_TASKS = "worker_visits_tasks"
ENABLE_PROGRAM_ACCESS_REDESIGN = "enable_program_access_redesign"
