# Generated by Django 4.2.30 on 2026-08-19 07:40

from django.db import migrations, models
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_organization_funder'),
        ('pghistory', '0007_auto_20250421_0444'),
        ('opportunity', '0144_completedworkinvoice_is_delta'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunitySupervisingOrganizationEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='opportunity',
            trigger=pgtrigger.compiler.Trigger(name='supervising_organization_insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "opportunity_opportunitysupervisingorganizationevent" ("pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "supervising_organization_id") VALUES (_pgh_attach_context(), NOW(), \'supervising_organization_insert\', NEW."id", NEW."supervising_organization_id"); RETURN NULL;', hash='b982e18be6bface314ff7520d104882e5c8a4ec2', operation='INSERT', pgid='pgtrigger_supervising_organization_insert_insert_cbb40', table='opportunity_opportunity', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='opportunity',
            trigger=pgtrigger.compiler.Trigger(name='supervising_organization_update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."supervising_organization_id" IS DISTINCT FROM (NEW."supervising_organization_id"))', func='INSERT INTO "opportunity_opportunitysupervisingorganizationevent" ("pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "supervising_organization_id") VALUES (_pgh_attach_context(), NOW(), \'supervising_organization_update\', NEW."id", NEW."supervising_organization_id"); RETURN NULL;', hash='28af32e2c63086efa1f671b1ed4faf0417c2b889', operation='UPDATE', pgid='pgtrigger_supervising_organization_update_update_87c3a', table='opportunity_opportunity', when='AFTER')),
        ),
        migrations.AddField(
            model_name='opportunitysupervisingorganizationevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='opportunitysupervisingorganizationevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='supervising_organization_events', to='opportunity.opportunity'),
        ),
        migrations.AddField(
            model_name='opportunitysupervisingorganizationevent',
            name='supervising_organization',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='organization.organization'),
        ),
    ]
