# Generated by Django 5.2.17 on 2026-09-08 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0145_opportunitysupervisingorganizationevent_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='completedwork',
        #     name='invoice',
        # ),
    ]
